### ISSUE TITLE
The file has been renamed to .pyw but the console still appears at startup.

### ISSUE THREAD

**Issue by bulletproof2k** [lazylibrarian/LazyLibrarian#51]
I renamed the startup file and created a shortcut in the startup folder, but the console still appears when the system starts. (Windows)
[lazylibrarian.log](https://github.com/lazylibrarian/LazyLibrarian/files/13760038/lazylibrarian.log)

**Comment by robertolopezlopez** [comment]
maybe you need to clean the `.pyc` as well
